## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'srs'  #to be modified, for instance daqmx then rename the module name:
# (pymodaq_plugins_srs become pymodaq_plugins_daqmx for instance)

package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_stanford_research_systems' #to modify
description = 'Set of plugins for the Stanford Research Systems (SRS) Instruments'

author = 'Sebastien. J. Weber'
author-email = 'sebastien.weber@cemes.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pymodaq>=4.0.0', 'pyvisa']

[features]  # defines the plugin features contained into this plugin
instruments = true  # true if plugin contains instrument classes (else false, notice the lowercase for toml files)
extensions = false  # true if plugins contains dashboard extensions
pid_models = false  # true if plugins contains pid models
h5exporters = false  # true if plugin contains custom h5 file exporters
scanners = false  # true if plugin contains custom scan layout (daq_scan extensions)

